trainer: vo
model:
  no_depth: False
  no_rgb: True
  encoder:
    type: resnet18
    depth: 5
    weights: null
    in_channels: 2
    in_height: 180
    in_width: 320
    base_planes: 32
    ngroups: 16 # base_planes // 2
    num_compression_channels: 35 # 2100 - flat size
  fc:
    hidden_size: 512
    output_size: 4
    p_dropout: 0.2
  collision_embedding_size: 0
  action_embedding_size: 16
data:
  path: /media/../Secondario/vodata
  split: train
  dim: 3
  rgb: True
  depth: True
  aug: ["Flip", "Swap"]
  p: 0.5
opt:
  lr: 1e-4
  b_size: 32
  patience: 3
  max_iter: 100
